=== abdoulfatah/TPSM1/xml/recettes.xsd
<?xml version="1.0" encoding="ISO-8859"?>
<!-- W3C Schema generated by XMLSpy v2016 rel. 2 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!--Déclaration globale des éléments-->
  <xs:element name="nom">
    <xs:simpleType>
      <xs:restriction base="xs:string">
	<xs:minLength value="2"/>
	<xs:maxLength value="40"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="prenom">
    <xs:simpleType>
      <xs:restriction base="xs:string">
	<xs:minLength value="2"/>
	<xs:maxLength value="40"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="nom-court">
    <xs:simpleType>
      <xs:restriction base="xs:string">
	<xs:minLength value="1"/>
	<xs:maxLength value="20"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="identificateur" type="xs:string"/>
  <xs:element name="resume" type="xs:string"/>
  <xs:element name="photo" type="xs:string"/>
  <xs:element name="date_publication" type="xs:date"/>
  <xs:element name="difficulte" type="xs:string"/>
  <xs:element name="nom_ingredient" type="xs:string">
    <xs:keyref name="ref_ingredient" refer="key_ingredient">
      <xs:selector xpath="root/liste_ingredients/ingredient"/>
      <xs:field xpath="@id"/>
    </xs:keyref>
  </xs:element>
  <xs:element name="nom_sous-categorie" type="xs:string">
    <xs:keyref name="ref_sous-categorie" refer="key_sous-categorie">
      <xs:selector xpath="root/liste_categories/categorie/sous-categorie"/>
      <xs:field xpath="@id"/>
    </xs:keyref>
  </xs:element>
  <xs:element name="nom_recette" type="xs:string">
    <xs:keyref name="ref_recette" refer="key_recette">
      <xs:selector xpath="root/liste_recettes/recette"/>
      <xs:field xpath="@id"/>
    </xs:keyref>
  </xs:element>
  <xs:element name="nom_auteur" type="xs:string">
    <xs:keyref name="ref_auteur" refer="key_auteur">
      <xs:selector xpath="root/liste_auteurs/auteur"/>
      <xs:field xpath="@id"/>
    </xs:keyref>
  </xs:element>
  <xs:element name="nom_categorie" type="xs:string">
    <xs:keyref name="ref_categorie" refer="key_categorie">
      <xs:selector xpath="root/liste_categories/categorie"/>
      <xs:field xpath="@id"/>
    </xs:keyref>
  </xs:element>
  <xs:element name="nbre_personnes" type="xs:integer"/>
  <xs:element name="Preparation" type="xs:string"/>
  <xs:element name="Cuisson" type="xs:string"/>
  <xs:element name="Repos" type="xs:string"/>
  <xs:element name="instructions" type="xs:string"/>
  <xs:element name="note" type="xs:integer"/>
  <xs:element name="Apport_energetique" type="xs:string"/>
  <xs:element name="Apport_nutritif" type="xs:string"/>
  <xs:element name="saison" type="xs:string"/>
  <xs:element name="descriptif" type="xs:string"/>
  <xs:element name="idext" type="xs:string"/>
  <xs:element name="pays" type="xs:string" default="France"/>
  <xs:element name="sexe">
    <xs:simpleType>
      <xs:restriction base="xs:string">
	<xs:enumeration value="Homme"/>
	<xs:enumeration value="Femme"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="biographie" type="xs:string" default="NULL"/>
  
  <!--Recette-->
  <xs:element name="recette">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="nom"/>
	<xs:element ref="identificateur"/>
	<xs:element ref="resume" minOccurs="0" maxOccurs="1"/>
	<xs:element ref="photo"/>
	<xs:element ref="date_publication"/>
	<xs:element ref="difficulte"/>
	<xs:element ref="nom_ingredient" minOccurs="2" maxOccurs="20"/>
	<xs:element ref="nom_sous-categorie"/>
	<xs:element ref="nbre_personnes"/>
	<xs:element ref="Preparation"/>
	<xs:element ref="Cuisson"/>
	<xs:element ref="Repos"/>
	<xs:element ref="instructions"/>
	<xs:element ref="nom_auteur"/>
	<xs:element ref="note" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
    <xs:key name="key_recette">
      <xs:selector xpath="root"/>
      <xs:field xpath="@id"/>
    </xs:key>
  </xs:element>
  
  <!--Ingrédient-->
  <xs:element name="ingredient">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="nom"/>
	<xs:element ref="Apport_energetique" minOccurs="0" maxOccurs="1"/>
	<xs:element ref="Apport_nutritif" minOccurs="0" maxOccurs="1"/>
	<xs:element ref="saison" minOccurs="0" maxOccurs="1"/>
	<xs:element ref="nom_recette" minOccurs="0" maxOccurs="unbounded"/>
	<xs:element ref="descriptif"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
    <xs:key name="key_ingredient">
      <xs:selector xpath="root"/>
      <xs:field xpath="@id"/>
    </xs:key>
  </xs:element>
  
  <!--<xs:element name="auteur">
      <xs:complexType>
      <xs:sequence>
      <xs:element ref="idext"/>
      <xs:element ref="nom" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="prenom" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="pays"/>
      <xs:element ref="sexe"/>
      <xs:element ref="nom_recette" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="biographie"/>
      <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID" use="required"/>
      </xs:complexType>
      </xs:element>-->
  <!--Utilisation d'un type personnalisé "base_auteur" et "auteur_avec_any" pour permettre l'héritage (cf. plus bas)-->
  <xs:complexType name="base_auteur">
    <xs:sequence>
      <xs:element ref="idext"/>
      <xs:element ref="nom" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="prenom" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="pays"/>
      <xs:element ref="sexe"/>
      <xs:element ref="nom_recette" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="biographie"/>
      <!--Bien que les biographies soient au départ optionelles, j'ai dû les rendre obligatoires (avec une valeur par défaut) pour  pouvoir utiliser "any"-->
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
  </xs:complexType>
  <xs:complexType name="auteur_avec_any">
    <xs:complexContent>
      <xs:extension base="base_auteur">
	<xs:sequence>
	  <xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <!--Auteur-->
  <xs:element name="auteur" type="auteur_avec_any">
    <xs:key name="key_auteur">
      <xs:selector xpath="root"/>
      <xs:field xpath="@id"/>
    </xs:key>
  </xs:element>
  
  <!--Catégorie-->
  <xs:element name="categorie">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="nom"/>
	<xs:element ref="nom-court" minOccurs="0" maxOccurs="1"/>
	<xs:element ref="descriptif"/>
	<xs:element ref="sous-categorie" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
    <xs:key name="key_categorie">
      <xs:selector xpath="root"/>
      <xs:field xpath="@id"/>
    </xs:key>
  </xs:element>
  <xs:element name="sous-categorie">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="nom"/>
	<xs:element ref="nom-court" minOccurs="0" maxOccurs="1"/>
	<xs:element ref="descriptif"/>
	<xs:element ref="nom_categorie"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
    <xs:key name="key_sous-categorie">
      <xs:selector xpath="root"/>
      <xs:field xpath="@id"/>
    </xs:key>
  </xs:element>
 
  <!-- Schéma XML à proprement parler-->
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
	<xs:element name="liste_recettes">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element ref="recette" minOccurs="0" maxOccurs="unbounded"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>
	<xs:element name="liste_ingredients">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element ref="ingredient" minOccurs="0" maxOccurs="unbounded"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>
	<xs:element name="liste_auteurs">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element ref="auteur" minOccurs="0" maxOccurs="unbounded"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>
	<xs:element name="liste_categories">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element ref="categorie" minOccurs="0" maxOccurs="unbounded"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!--Extension et restriction des types complexes : exemples-->
  <!--Type personne héritant de base_auteur car auteur_avec_any créerait une ambiguïté-->
  <xs:complexType name="personne">
    <xs:complexContent>
      <xs:extension base="base_auteur">
	<xs:sequence>
	  <xs:element name="titre">
	    <xs:simpleType>
	      <xs:restriction base="xs:string">
		<xs:pattern value="amateur|confirme|chef|Gordon Ramsay"/>
	      </xs:restriction>
	    </xs:simpleType>
	  </xs:element>
	</xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
 
  <!--Types recettes de la catégorie entrées chaudes dérivé de recette-->
  <xs:element name="recette_entrees_chaudes">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="nom"/>
	<xs:element ref="identificateur"/>
	<xs:element ref="resume" minOccurs="0" maxOccurs="1"/>
	<xs:element ref="photo"/>
	<xs:element ref="date_publication"/>
	<xs:element ref="difficulte"/>
	<xs:element ref="nom_ingredient" minOccurs="2" maxOccurs="20"/>
	<xs:element name="nom_sous-categorie">
	  <xs:simpleType>
	    <xs:restriction base="xs:string">
	      <xs:pattern value="SC2"/>
	    </xs:restriction>
	  </xs:simpleType>
	</xs:element>
	<xs:element ref="nbre_personnes"/>
	<xs:element ref="Preparation"/>
	<xs:element ref="Cuisson"/>
	<xs:element ref="Repos"/>
	<xs:element ref="instructions"/>
	<xs:element ref="nom_auteur"/>
	<xs:element ref="note" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== abdoulfatah/TPSM1/xml/recettes.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="recettes.xsd">
	<liste_recettes>
		<recette id="r2830">
			<nom>Cake à la tomate farcie</nom>
			<identificateur>r2830-Cake à la tomate farcie</identificateur>
			<resume>- Cake à la tomate farcie - Recettes de cuisine Ôdelices</resume>
			<photo>http://www.odelices.com/images/recettes/cake-a-la-tomate-farcie.jpg</photo>
			<date_publication>2011-04-24</date_publication>
			<difficulte>Très facile</difficulte>
			<nom_ingredient>farine</nom_ingredient>
			<nom_ingredient>levure chimique</nom_ingredient>
			<nom_ingredient>lait</nom_ingredient>
			<nom_ingredient>oeuf</nom_ingredient>
			<nom_ingredient>huile d'olive</nom_ingredient>
			<nom_ingredient>fromage</nom_ingredient>
			<nom_ingredient>t142</nom_ingredient>
			<nom_ingredient> fromage de brebis</nom_ingredient>
			<nom_ingredient>t120</nom_ingredient>
			<nom_ingredient> Sel</nom_ingredient>
			<nom_ingredient>poivre</nom_ingredient>
			<nom_sous-categorie>SC1</nom_sous-categorie>
			<nbre_personnes>6</nbre_personnes>
			<Preparation>20min</Preparation>
			<Cuisson>25min</Cuisson>
			<Repos/>
			<instructions>1. Inciser le fond de chaque tomate et vider les graines à l'aide d'une toute petite cuillère (j'ai fait avec le manche d'une cuillère à moka).
      Saler l'interieur de chaque tomate et deposer sur un papier absorbant, elles vont degorger.
      
      2. Beurrer et fariner 6 ramequins. Prechauffer le four à 180°C.
      3. Faire tiedir le lait 20-30 secondes au micro-onde. Battre l'oeuf en omelette, saler et poivrer puis ajouter la farine, la levure, le lait et l'huile. 
      Ajouter le fromage râpe.
      4. Dans un bol melanger la fêta et le thon egoutte à l'aide d'une fourchette et farcir les tomates avec cette preparation.
      
      5. Remplir les moules avec la pâte et deposer une tomate dans chaque en l'enfonçant au deux tiers du moule.
      
      6. Cuire entre 20 et 25 minutes.</instructions>
			<nom_auteur>AUT3</nom_auteur>
		</recette>
		<recette id="r3136">
			<nom>Petits cakes au chèvre et myrtilles</nom>
			<identificateur>r3136-Petits cakes au chèvre frais et myrtilles</identificateur>
			<resume>- Petits cakes au chèvre frais et myrtilles - les meilleures recettes de cuisine d'Ôdelices</resume>
			<photo>http://www.odelices.com/images/recettes/petits-cakes-au-chevre-frais-et-myrtilles.jpg</photo>
			<date_publication>2012-04-09</date_publication>
			<difficulte>Très facile</difficulte>
			<nom_ingredient>farine</nom_ingredient>
			<nom_ingredient>lait</nom_ingredient>
			<nom_ingredient>oeuf</nom_ingredient>
			<nom_ingredient>huile d'olive</nom_ingredient>
			<nom_ingredient> fromage de chèvre</nom_ingredient>
			<nom_ingredient>bicarbonate de sodium</nom_ingredient>
			<nom_ingredient>barquette de myrtilles lavees</nom_ingredient>
			<nom_sous-categorie>SC1</nom_sous-categorie>
			<nbre_personnes>6</nbre_personnes>
			<Preparation>10min</Preparation>
			<Cuisson>17min</Cuisson>
			<Repos/>
			<instructions>1. Dans un saladier, melangez la farine, le sel, le bicarbonate, les oeufs, le lait et l'huile.
      2. Quand la pâte est belle, versez-la dans de petits moules à cake huiles.
      3. Repartissez sur les cakes de petits morceaux de fromage et les myrtilles.
      4. Faites cuire 17 minutes à 180°C four ventile. Piquez un cake à l'aide de la pointe d'un couteau afin de verifier la cuisson.
      5. Servez à temperature ambiante avec une salade croquante.</instructions>
			<nom_auteur>AUT2</nom_auteur>
			<note>5</note>
		</recette>
		<recette id="r4275">
			<nom>Mozzarella panee</nom>
			<identificateur>r4275-Mozzarella panee</identificateur>
			<resume>- Pour un soir de semaine, si vous voulez faire une salade express mais epatante, faites de la mozzarella panee ! C'est rapide, facile et très syma !</resume>
			<photo>http://www.odelices.com/images/recettes/mozzarella_panee.jpg</photo>
			<date_publication>2015-02-08</date_publication>
			<difficulte>Très facile</difficulte>
			<nom_ingredient>boules de mozzarella de bufflone</nom_ingredient>
			<nom_ingredient>oeuf</nom_ingredient>
			<nom_ingredient>farine</nom_ingredient>
			<nom_ingredient> chapelure</nom_ingredient>
			<nom_sous-categorie>SC2</nom_sous-categorie>
			<nbre_personnes>4</nbre_personnes>
			<Preparation>5min</Preparation>
			<Cuisson>5min</Cuisson>
			<Repos/>
			<instructions>1. Coupez les boules de mozzarella en rondelles.
      2. Mettez la farine et la chapelure dans deux assiettes. Et battez l'oeuf avec une fourchette dans un bol.
      3. Faites chauffer une poêle avec de l'huile.
      4. Faites tremper les rondelles de mozzarella dans la farine, puis dans l'oeuf et enfin dans la chapelure.
      5. Faites frire dans la poêle quelques minutes de chaque côte. Servez avec une salade verte.</instructions>
			<nom_auteur>AUT1</nom_auteur>
			<note>5</note>
		</recette>
		<recette id="r3289">
			<nom>Oeuf cocotte aux marrons</nom>
			<identificateur>r4275-Mozzarella panee</identificateur>
			<resume/>
			<photo>http://www.odelices.com/images/recettes/oeuf_cocotte_aux_marrons.jpg</photo>
			<date_publication>2012-11-22</date_publication>
			<difficulte>Très facile</difficulte>
			<nom_ingredient>marrons cuits et peles</nom_ingredient>
			<nom_ingredient>oeuf</nom_ingredient>
			<nom_ingredient>crème fraiche epaisse</nom_ingredient>
			<nom_ingredient> Sel</nom_ingredient>
			<nom_ingredient>poivre</nom_ingredient>
			<nom_sous-categorie>SC2</nom_sous-categorie>
			<nbre_personnes>4</nbre_personnes>
			<Preparation>5min</Preparation>
			<Cuisson>15min</Cuisson>
			<Repos/>
			<instructions>1. Hachez grossièrement les marrons cuits. Repartissez-les dans 4 ramequins inviduels.
      2. Repartissez une cuillère de crème sur les marrons.
      3. Puis cassez les oeufs et ajoutez-en un dans chaque ramequin, en les posant delicatement pour ne pas casser le jaune. Salez et poivrez.
      4. Placez les ramequins dans le four prechauffe à 180°C, au bain-marie. Faites cuire 15 min jusqu'à ce que le blanc soit bien pris.
      5. Servez chaud, avec des mouillettes de pain grille.</instructions>
			<nom_auteur>AUT1</nom_auteur>
		</recette>
		<recette id="r4315">
			<nom>Endives farcies au thon</nom>
			<identificateur>r4315-Endives farcies au thon</identificateur>
			<resume>-	

	Une salade « hebergee » dans une feuille d'endive ! Une idee gourmande qui ravira les plus jeunes qui pourront d'ailleurs vous aider à farcir les endives !</resume>
			<photo>http://www.odelices.com/images/recettes/endives_farcies_au_thon1.jpg</photo>
			<date_publication>2015-03-12</date_publication>
			<difficulte>Très facile</difficulte>
			<nom_ingredient>e300</nom_ingredient>
			<nom_ingredient>t120</nom_ingredient>
			<nom_ingredient>cornichons</nom_ingredient>
			<nom_ingredient>crème fraîche</nom_ingredient>
			<nom_ingredient>moutarde</nom_ingredient>
			<nom_ingredient>ciboulette</nom_ingredient>
			<nom_ingredient>t142</nom_ingredient>
			<nom_ingredient> Sel</nom_ingredient>
			<nom_ingredient>poivre</nom_ingredient>
			<nom_sous-categorie>SC3</nom_sous-categorie>
			<nbre_personnes>4</nbre_personnes>
			<Preparation>15min</Preparation>
			<Cuisson/>
			<Repos/>
			<instructions>1. Lavez les tomates, coupez-les en deux et epepinez-les. Emincez finement la ciboulette.
      2. Mettez dans le bol du robot le thon, les tomates, les cornichons, la crème fraîche, la moutarde et la ciboulette. Mixez le tout grossièrement pour garder quelques morceaux. Salez legèrement et poivrez eventuellement.
      3. Passez les endives sous l'eau rapidement et enlevez le cône amer à la base des feuilles. Detachez les feuilles une par une, sechez-les bien.
      4. Repartissez la farce dans les feuilles et servez bien frais.</instructions>
			<nom_auteur>AUT1</nom_auteur>
		</recette>
		<recette id="r1241">
			<nom>Moules et frites</nom>
			<identificateur>r1241-Moules et frites</identificateur>
			<resume>-	

	Si vous passez par le nord, prenez le temps de deguster des frites savoureuses dans une baraque à frites et n'oubliez pas de goûter à des moules de là-bas !
	Recettes extraites du livre Craquez pour la cuisine des chtis !</resume>
			<photo>http://www.odelices.com/images/recettes/moules-frites.jpg</photo>
			<date_publication>2006-06-01</date_publication>
			<difficulte>Très facile</difficulte>
			<nom_ingredient>moules</nom_ingredient>
			<nom_ingredient>oi16</nom_ingredient>
			<nom_ingredient>ech12</nom_ingredient>
			<nom_ingredient>branche de celeri</nom_ingredient>
			<nom_ingredient>bouquet garni</nom_ingredient>
			<nom_ingredient>vin blanc</nom_ingredient>
			<nom_ingredient>beurre</nom_ingredient>
			<nom_ingredient>pom06</nom_ingredient>
			<nom_ingredient>huile</nom_ingredient>
			<nom_ingredient> Sel</nom_ingredient>
			<nom_sous-categorie>SC16</nom_sous-categorie>
			<nbre_personnes>4</nbre_personnes>
			<Preparation>15min</Preparation>
			<Cuisson>30 min</Cuisson>
			<Repos/>
			<instructions>Pour les moules1. Grattez les moules et rincez-les soigneusement.
      2. Pelez et emincez les echalotes et les oignons. Faites-les revenir sans coloration dans une grande sauteuse ou une cocotte avec le beurre 2 à 3 minutes à feu vif.
      3. Ajoutez les moules, le bouquet garni et le celeri. Mouillez avec le vin blanc.
      4. Couvrez et laissez cuire à feu vif jusqu' à ce que les moules s'ouvrent complètement (5 minutes environ)..
      5. Versez les moules et leur jus dans un plat creux. Servez avec les frites et une bière blonde.Pour les frites : 
	1. epluchez les pommes de terre et coupez-les en larges bâtonnets. Lavez-les et essuyez-les soigneusement dans un torchon propre (pour retirer l'amidon).
	2. Faites chauffer l'huile de friture à 180°C.
	3. Plongez les frites et laissez-les cuire 10 à 15 minutes. Remontez-les à la surface et laissez-les s'egoutter quelques minutes.
